trigger:
- main

pool:
  name: Default  # The agent pool where your VM agent is registered
  demands:
  - agent.name -equals <YOUR-VM-AGENT-NAME>

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy Job'
  pool:
    name: Default  # Ensure this matches the agent pool name
  steps:
  - script: echo "Running on a self-hosted agent VM"
    displayName: 'Print a message'
  - script: |
      echo "Building the application..."
      # Add your build commands here
    displayName: 'Build Step'
  - script: |
      echo "Deploying the application..."
      # Add your deploy commands here
    displayName: 'Deploy Step'