name: Trigger-Azure-Pipeline
on:
  pull_request:
    types: [closed]
  status:
    branches:
      - development
      - master
jobs:
  trigger-pipeline:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger Azure Pipeline
      env:
        AZURE_DEVOPS_ORG: 'power-poc'  
        AZURE_DEVOPS_PROJECT: 'powerbi'
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      run: |
        if (${{ github.event_name}} == 'pull_request' && ${{ github.event.action}} == 'closed' && ${{ github.event.pull_request.merged}} == true) then
          if [[ "${{ github.ref }}" == "master" ]]; then
              AZURE_DEVOPS_PIPELINE_ID="1"
          elif [[ "${{ github.ref }}" == "development" ]]; then
              AZURE_DEVOPS_PIPELINE_ID="3"
          else
              AZURE_DEVOPS_PIPELINE_ID="4"
          fi
          pipeline_url="https://dev.azure.com/$AZURE_DEVOPS_ORG/$AZURE_DEVOPS_PROJECT/_apis/pipelines/$AZURE_DEVOPS_PIPELINE_ID/runs?api-version=6.0-preview.1"
          
          echo "Triggering Azure Pipeline Only Master branch: $pipeline_url from GitHub Actions"
          
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic $(echo -n ":$AZURE_DEVOPS_PAT" | base64)" \
            $pipeline_url)

          if [ $response -ne 201 ]; then
            echo "Failed to trigger Azure Pipeline. HTTP status code: $response"
            exit 1
          else
            echo "Successfully triggered Azure Pipeline $AZURE_DEVOPS_PIPELINE_ID"
          fi
        fi